I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/helpers.rpy", line 139, in script
    python:
  File "game/helpers.rpy", line 140, in <module>
    send_to_server('Wolf')
  File "game/helpers.rpy", line 26, in send_to_server
    client_socket.sendall(message.encode('utf-8'))
error: [Errno 32] Broken pipe

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/helpers.rpy", line 139, in script
    python:
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/helpers.rpy", line 140, in <module>
    send_to_server('Wolf')
  File "game/helpers.rpy", line 26, in send_to_server
    client_socket.sendall(message.encode('utf-8'))
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/socket.py", line 228, in meth
error: [Errno 32] Broken pipe

Linux-5.4.0-110-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
RenPyTest 1.0
Fri May 27 20:45:07 2022
